server:
  port: 3344
spring:
  application:
    name: cloud-config-center
  cloud:
    config:
      label: master
      server:
        git:
          uri: https://github.com/wang-so/springcloud-config.git
          skip-ssl-validation: true
          search-paths:
            - springcloud-config
          force-pull: true

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka
